import { config } from "./config.js";
import { t } from "./utils.js";

const storedCount = localStorage.getItem("mecano_word_count");

export const data = {
  wordsListES: [],
  wordsListEN: [],
  wordsListDE: [],
  wordsListFR: [],
  wordsListPT: [],
  wordCount:
    storedCount === "infinite" ? "infinite" : parseInt(storedCount) || 25,
};

export const i18n = {
  en: {
    "nav.github": "GitHub Repository",
    "settings.language": "Language:",
    "settings.lang.es": "Spanish",
    "settings.lang.de": "German",
    "settings.lang.en": "English",
    "settings.lang.fr": "French",
    "settings.lang.pt": "Portuguese",
    "settings.mode": "Mode:",
    "settings.mode.words": "Words",
    "settings.mode.time": "Time",
    "settings.time": "Time (s):",
    "settings.words": "Words:",
    "settings.infinite": "Infinite",
    "settings.generationMode": "Generation Mode:",
    "settings.random": "Random",
    "settings.learning": "Learning",
    "settings.theme": "Theme:",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.zenMode": "Zen Mode:",
    "settings.off": "Off",
    "settings.on": "On",
    "actions.backToGame": "Back to Game",
    "actions.resetHistory": "Reset History",
    "actions.restart": "RESTART",
    "tooltips.numbers": "Numbers",
    "tooltips.uppercase": "Uppercase",
    "tooltips.symbols": "Symbols",
    "tooltips.suddenDeath": "Sudden Death",
    "tooltips.zenMode": "Zen Mode",
    "tooltips.sound": "Sound",
    "tooltips.statistics": "Statistics",
    "tooltips.settings": "Settings",
    "results.title": "RESULTS",
    "results.wpm": "WPM",
    "results.accuracy": "ACCURACY",
    "results.errors": "ERRORS",
    "results.weakKeys": "Weak keys:",
    "results.none": "None",
    "stats.tabs.profile": "Profile",
    "stats.tabs.keys": "Key Analysis",
    "stats.profile.started": "Tests Started",
    "stats.profile.completed": "Tests Completed",
    "stats.profile.time": "Time Typing",
    "stats.profile.records": "Personal Records (WPM)",
    "stats.records.normal": "Normal",
    "stats.records.all": "All",
    "stats.filters.all": "All",
    "stats.filters.lowercase": "a-z",
    "stats.filters.uppercase": "A-Z",
    "stats.filters.accents": "á-ü",
    "stats.filters.numbers": "0-9",
    "stats.filters.symbols": "#@!",
    "stats.headers.key": "Key",
    "stats.headers.total": "Total",
    "stats.headers.errors": "Errors",
    "stats.headers.errorRate": "% Error",
    "stats.noData": "No data yet",
    "alerts.capsLock": "Caps Lock is ON",
    "alerts.resetHistory":
      "Are you sure you want to reset all your learning history?",
    "alerts.loadWords":
      "To load words from words.json, you need to run this project on a local server (due to CORS security policies). If you use VS Code, install the 'Live Server' extension and click 'Go Live'.",
    "modal.confirm": "Confirm",
    "modal.cancel": "Cancel",
    "toast.statsReset": "Statistics reset successfully",
    "toast.newRecord": "New personal record!",
    "shortcuts.restart": "Restart",
  },
  es: {
    "nav.github": "Repositorio de GitHub",
    "settings.language": "Idioma:",
    "settings.lang.es": "Español",
    "settings.lang.de": "Alemán",
    "settings.lang.en": "Inglés",
    "settings.lang.fr": "Francés",
    "settings.lang.pt": "Portugués",
    "settings.mode": "Modo:",
    "settings.mode.words": "Palabras",
    "settings.mode.time": "Tiempo",
    "settings.time": "Tiempo (s):",
    "settings.words": "Palabras:",
    "settings.infinite": "Infinito",
    "settings.generationMode": "Modo de generación:",
    "settings.random": "Aleatorio",
    "settings.learning": "Aprendizaje",
    "settings.theme": "Tema:",
    "settings.light": "Claro",
    "settings.dark": "Oscuro",
    "settings.zenMode": "Modo zen:",
    "settings.off": "Desactivado",
    "settings.on": "Activado",
    "actions.backToGame": "Volver al juego",
    "actions.resetHistory": "Restablecer historial",
    "actions.restart": "REINICIAR",
    "tooltips.numbers": "Números",
    "tooltips.uppercase": "Mayúsculas",
    "tooltips.symbols": "Símbolos",
    "tooltips.suddenDeath": "Muerte súbita",
    "tooltips.zenMode": "Modo zen",
    "tooltips.sound": "Sonido",
    "tooltips.statistics": "Estadísticas",
    "tooltips.settings": "Configuración",
    "results.title": "RESULTADOS",
    "results.wpm": "WPM",
    "results.accuracy": "PRECISIÓN",
    "results.errors": "ERRORES",
    "results.weakKeys": "Teclas débiles:",
    "results.none": "Ninguna",
    "stats.tabs.profile": "Perfil",
    "stats.tabs.keys": "Análisis de Teclas",
    "stats.profile.started": "Tests Iniciados",
    "stats.profile.completed": "Tests Completados",
    "stats.profile.time": "Tiempo Escribiendo",
    "stats.profile.records": "Récords Personales (WPM)",
    "stats.records.normal": "Normal",
    "stats.records.all": "Todo",
    "stats.filters.all": "Todos",
    "stats.filters.lowercase": "a-z",
    "stats.filters.uppercase": "A-Z",
    "stats.filters.accents": "á-ü",
    "stats.filters.numbers": "0-9",
    "stats.filters.symbols": "#@!",
    "stats.headers.key": "Tecla",
    "stats.headers.total": "Total",
    "stats.headers.errors": "Errores",
    "stats.headers.errorRate": "% Error",
    "stats.noData": "Sin datos",
    "alerts.capsLock": "Bloq Mayús activado",
    "alerts.resetHistory":
      "¿Estás seguro de que quieres borrar todo tu historial de aprendizaje?",
    "alerts.loadWords":
      "Para cargar las palabras desde words.json, debes ejecutar este proyecto en un servidor local (por políticas de seguridad CORS). Si usas VS Code, instala la extensión 'Live Server' y haz clic en 'Go Live'.",
    "modal.confirm": "Confirmar",
    "modal.cancel": "Cancelar",
    "toast.statsReset": "Estadísticas restablecidas correctamente",
    "toast.newRecord": "¡Nuevo récord personal!",
    "shortcuts.restart": "Reiniciar",
  },
  de: {
    "nav.github": "GitHub-Repository",
    "settings.language": "Sprache:",
    "settings.lang.es": "Spanisch",
    "settings.lang.de": "Deutsch",
    "settings.lang.en": "Englisch",
    "settings.lang.fr": "Französisch",
    "settings.lang.pt": "Portugiesisch",
    "settings.mode": "Modus:",
    "settings.mode.words": "Wörter",
    "settings.mode.time": "Zeit",
    "settings.time": "Zeit (s):",
    "settings.words": "Wörter:",
    "settings.infinite": "Unendlich",
    "settings.generationMode": "Generierungsmodus:",
    "settings.random": "Zufällig",
    "settings.learning": "Lernmodus",
    "settings.theme": "Thema:",
    "settings.light": "Hell",
    "settings.dark": "Dunkel",
    "settings.zenMode": "Zen-Modus:",
    "settings.off": "Aus",
    "settings.on": "An",
    "actions.backToGame": "Zurück zum Spiel",
    "actions.resetHistory": "Verlauf zurücksetzen",
    "actions.restart": "NEUSTART",
    "tooltips.numbers": "Zahlen",
    "tooltips.uppercase": "Großbuchstaben",
    "tooltips.symbols": "Symbole",
    "tooltips.suddenDeath": "Plötzlicher Tod",
    "tooltips.zenMode": "Zen-Modus",
    "tooltips.sound": "Ton",
    "tooltips.statistics": "Statistiken",
    "tooltips.settings": "Einstellungen",
    "results.title": "ERGEBNISSE",
    "results.wpm": "WPM",
    "results.accuracy": "GENAUIGKEIT",
    "results.errors": "FEHLER",
    "results.weakKeys": "Schwache Tasten:",
    "results.none": "Keine",
    "stats.tabs.profile": "Profil",
    "stats.tabs.keys": "Tastenanalyse",
    "stats.profile.started": "Tests Gestartet",
    "stats.profile.completed": "Tests Abgeschlossen",
    "stats.profile.time": "Tippzeit",
    "stats.profile.records": "Persönliche Rekorde (WPM)",
    "stats.filters.all": "Alle",
    "stats.filters.lowercase": "a-z",
    "stats.filters.uppercase": "A-Z",
    "stats.filters.accents": "ä-ü",
    "stats.filters.numbers": "0-9",
    "stats.filters.symbols": "#@!",
    "stats.headers.key": "Taste",
    "stats.headers.total": "Total",
    "stats.headers.errors": "Fehler",
    "stats.headers.errorRate": "% Fehler",
    "stats.noData": "Noch keine Daten",
    "alerts.capsLock": "Feststelltaste ist AN",
    "alerts.resetHistory":
      "Möchtest du wirklich deinen gesamten Lernverlauf zurücksetzen?",
    "alerts.loadWords":
      "Um Wörter aus words.json zu laden, musst du dieses Projekt auf einem lokalen Server ausführen (wegen CORS-Sicherheitsrichtlinien). Wenn du VS Code nutzt, installiere die Erweiterung 'Live Server' und klicke auf 'Go Live'.",
    "modal.confirm": "Bestätigen",
    "modal.cancel": "Abbrechen",
    "toast.statsReset": "Statistiken erfolgreich zurückgesetzt",
    "toast.newRecord": "Neuer persönlicher Rekord!",
    "shortcuts.restart": "Neustart",
  },
  fr: {
    "nav.github": "Dépôt GitHub",
    "settings.language": "Langue:",
    "settings.lang.es": "Espagnol",
    "settings.lang.de": "Allemand",
    "settings.lang.en": "Anglais",
    "settings.lang.fr": "Français",
    "settings.lang.pt": "Portugais",
    "settings.mode": "Mode:",
    "settings.mode.words": "Mots",
    "settings.mode.time": "Temps",
    "settings.time": "Temps (s):",
    "settings.words": "Mots:",
    "settings.infinite": "Infini",
    "settings.generationMode": "Mode de génération:",
    "settings.random": "Aléatoire",
    "settings.learning": "Apprentissage",
    "settings.theme": "Thème:",
    "settings.light": "Clair",
    "settings.dark": "Sombre",
    "settings.zenMode": "Mode zen:",
    "settings.off": "Désactivé",
    "settings.on": "Activé",
    "actions.backToGame": "Retour au jeu",
    "actions.resetHistory": "Réinitialiser l'historique",
    "actions.restart": "RECOMMENCER",
    "tooltips.numbers": "Nombres",
    "tooltips.uppercase": "Majuscules",
    "tooltips.symbols": "Symboles",
    "tooltips.suddenDeath": "Mort subite",
    "tooltips.zenMode": "Mode zen",
    "tooltips.sound": "Son",
    "tooltips.statistics": "Statistiques",
    "tooltips.settings": "Paramètres",
    "results.title": "RÉSULTATS",
    "results.wpm": "WPM",
    "results.accuracy": "PRÉCISION",
    "results.errors": "ERREURS",
    "results.weakKeys": "Touches faibles:",
    "results.none": "Aucune",
    "stats.tabs.profile": "Profil",
    "stats.tabs.keys": "Analyse des Touches",
    "stats.profile.started": "Tests Commencés",
    "stats.profile.completed": "Tests Terminés",
    "stats.profile.time": "Temps de Frappe",
    "stats.profile.records": "Records Personnels (WPM)",
    "stats.filters.all": "Tous",
    "stats.filters.lowercase": "a-z",
    "stats.filters.uppercase": "A-Z",
    "stats.filters.accents": "à-ü",
    "stats.filters.numbers": "0-9",
    "stats.filters.symbols": "#@!",
    "stats.headers.key": "Touche",
    "stats.headers.total": "Total",
    "stats.headers.errors": "Erreurs",
    "stats.headers.errorRate": "% Erreur",
    "stats.noData": "Aucune donnée",
    "alerts.capsLock": "Verr. Maj activé",
    "alerts.resetHistory":
      "Voulez-vous vraiment réinitialiser tout votre historique d'apprentissage ?",
    "alerts.loadWords":
      "Pour charger les mots depuis words.json, vous devez exécuter ce projet sur un serveur local (en raison des politiques de sécurité CORS). Si vous utilisez VS Code, installez l'extension 'Live Server' et cliquez sur 'Go Live'.",
    "modal.confirm": "Confirmer",
    "modal.cancel": "Annuler",
    "toast.statsReset": "Statistiques réinitialisées avec succès",
    "toast.newRecord": "Nouveau record personnel !",
    "shortcuts.restart": "Recommencer",
  },
  pt: {
    "nav.github": "Repositório GitHub",
    "settings.language": "Linguagem:",
    "settings.lang.es": "Espanhol",
    "settings.lang.de": "Alemão",
    "settings.lang.en": "Inglês",
    "settings.lang.fr": "Francês",
    "settings.lang.pt": "Português",
    "settings.mode": "Modo:",
    "settings.mode.words": "Palavras",
    "settings.mode.time": "Tempo",
    "settings.time": "Tempo (s):",
    "settings.words": "Palavras:",
    "settings.infinite": "Infinito",
    "settings.generationMode": "Modo de Geração:",
    "settings.random": "Aleatório",
    "settings.learning": "Aprendizado",
    "settings.theme": "Tema:",
    "settings.light": "Claro",
    "settings.dark": "Escuro",
    "settings.zenMode": "Modo Zen:",
    "settings.off": "Desligado",
    "settings.on": "Ligado",
    "actions.backToGame": "Voltar ao jogo",
    "actions.resetHistory": "Resetar histórico",
    "actions.restart": "Resetar",
    "tooltips.numbers": "Números",
    "tooltips.uppercase": "Maiúscula",
    "tooltips.symbols": "Símbolos",
    "tooltips.suddenDeath": "Morte Súbita",
    "tooltips.zenMode": "Modo Zen",
    "tooltips.sound": "Som",
    "tooltips.statistics": "Estatística",
    "tooltips.settings": "Configurações",
    "results.title": "RESULTADOS",
    "results.wpm": "PPM",
    "results.accuracy": "PRECISÃO",
    "results.errors": "ERROS",
    "results.weakKeys": "Teclas Fracas:",
    "results.none": "Nenhum",
    "stats.tabs.profile": "Perfil",
    "stats.tabs.keys": "Analise de Teclas",
    "stats.profile.started": "Testes Iniciados",
    "stats.profile.completed": "Testes Completos",
    "stats.profile.time": "Tempo Digitando",
    "stats.profile.records": "Recordes Pessoais (PPM)",
    "stats.records.normal": "Normal",
    "stats.records.all": "Todos",
    "stats.filters.all": "Todos",
    "stats.filters.lowercase": "a-z",
    "stats.filters.uppercase": "A-Z",
    "stats.filters.accents": "á-ü",
    "stats.filters.numbers": "0-9",
    "stats.filters.symbols": "#@!",
    "stats.headers.key": "Tecla",
    "stats.headers.total": "Total",
    "stats.headers.errors": "Erros",
    "stats.headers.errorRate": "% Erro",
    "stats.noData": "Sem dados",
    "alerts.capsLock": "Caps Lock ativado",
    "alerts.resetHistory":
      "Você tem certeza que quer resetar todo seu histórico de aprendizado?",
    "alerts.loadWords":
      "Para carregar palavras do arquivo words.json, você precisa executar este projeto em um servidor local (devido às políticas de segurança CORS). Se você usa o VS Code, instale a extensão 'Live Server' e clique em 'Go Live'.",
    "modal.confirm": "Confirmar",
    "modal.cancel": "Cancelar",
    "toast.statsReset": "Estatísticas resetadas com sucesso!",
    "toast.newRecord": "Novo recorde pessoal!",
    "shortcuts.restart": "Resetar",
  },
};

export function applyTranslations() {
  document.documentElement.lang = config.currentLanguage;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    el.textContent = t(el.dataset.i18n);
  });
  document.querySelectorAll("[data-i18n-title]").forEach((el) => {
    el.setAttribute("title", t(el.dataset.i18nTitle));
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
    el.setAttribute("placeholder", t(el.dataset.i18nPlaceholder));
  });
  document.querySelectorAll("[data-i18n-aria]").forEach((el) => {
    el.setAttribute("aria-label", t(el.dataset.i18nAria));
  });
}

export async function loadWords() {
  try {
    const response = await fetch("words.json");
    const json = await response.json();
    data.wordsListES = json.es || [];
    data.wordsListEN = json.en || [];
    data.wordsListDE = json.de || [];
    data.wordsListFR = json.fr || [];
    data.wordsListPT = json.pt || [];
  } catch (error) {
    console.error("Error loading words:", error);
    data.wordsListES = ["error", "loading", "words", "check", "console"];
    data.wordsListEN = ["error", "loading", "words", "check", "console"];
    data.wordsListDE = ["fehler", "laden", "wörter", "überprüfen", "konsole"];
    data.wordsListFR = ["erreur", "chargement", "mots", "vérifier", "console"];
    data.wordsListPT = ["erro", "carregando", "palavras", "verificar", "console"];
    alert(t("alerts.loadWords"));
  }
}
